### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ghost** [Microdent/Handwritten_Mathematical_Calculator_on_FPGA#3]
您好，您的这个项目给了我很大的帮助，但是我在是同Tensorflow时遇到了版本不兼容的问题，多以想请问一下，您使用的Python,Tensorflow,Numpy都具体是哪一个版本，非常感谢您和您的这个项目！

**Comment by Microdent** [comment]
好的，多谢肯定，最近比较忙，所以没有及时回复。版本信息如下：
Python 3.7.6、Tensorflow 1.15.0、Numpy 1.19.1

**Comment by Microdent** [comment]
好的，多谢肯定，最近比较忙，所以没有及时回复。版本信息如下：
Python 3.7.6、Tensorflow 1.15.0、Numpy 1.19.1

**Comment by ghost** [comment]
> 好的，多谢肯定，最近比较忙，所以没有及时回复。版本信息如下：
> Python 3.7.6、Tensorflow 1.15.0、Numpy 1.19.1
非常感谢！！
