### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by AshersHub** [Microdent/Handwritten_Mathematical_Calculator_on_FPGA#4]
前辈您好，仔细研究过您的工程文件，对我的帮助非常大，但部署到PYNQ-Z1开发板后发现无法加载overlays，查阅资料发现需要.tcl格式文件，您可以不吝赐教一下嘛？万分感激!

**Comment by Microdent** [comment]
Hardware_Project/Block_Design文件夹中的README.md文件中有一句话是加了删除线的，那就是针对老版本PYNQ的img镜像需要tcl文件时如何获取tcl文件的方法，如果你使用新版本的PYNQ镜像应该是使用hwh文件即可。

**Comment by AshersHub** [comment]
谢谢前辈～在没有tcl 文件的前提下，我试了一下，用2.6版本的会报错，用2.4版本的会给提示，但能正常运行～再次感谢🙏 在2021年03月30日 21:44，Microd 写道： 

Hardware_Project/Block_Design文件夹中的README.md文件中有一句话是加了删除线的，那就是针对老版本PYNQ的img镜像需要tcl文件时如何获取tcl文件的方法，如果你使用新版本的PYNQ镜像应该是使用hwh文件即可。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Microdent/Handwritten_Mathematical_Calculator_on_FPGA/issues/4#issuecomment-810260504",

"url": "https://github.com/Microdent/Handwritten_Mathematical_Calculator_on_FPGA/issues/4#issuecomment-810260504",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
