### ISSUE TITLE
Vivado version

### ISSUE THREAD

**Issue by shobhitt10** [Microdent/Handwritten_Mathematical_Calculator_on_FPGA#6]
Hi, which vivado version did you use?

**Comment by Microdent** [comment]
Hi, @shobhitt10 ,the vivado version is 2019.2, you find versions of all tools at [here](https://github.com/Microdent/Handwritten_Mathematical_Calculator_on_FPGA#0-prerequisites).

**Comment by Microdent** [comment]
Hi, @shobhitt10 ,the vivado version is 2019.2, you can find versions of all tools at [here](https://github.com/Microdent/Handwritten_Mathematical_Calculator_on_FPGA#0-prerequisites).
