### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Ronin3502** [Microdent/Handwritten_Mathematical_Calculator_on_FPGA#7]
您好！您的项目对我很有指导意义，但由于我新进入这个领域，对HLS还不太熟悉，有一些问题想请教一下，还望不吝赐教。

首先，我将您的cnn.cpp和cnn.h放入vivado HLS工程中，并进行了综合，但报告看不出latency相关的情况，请问是什么原因呢？
![latency的问题](https://user-images.githubusercontent.com/49109408/156536800-05911830-37a6-4afa-801f-461f5bfa03a8.png)

第二，请问cnn.cpp中已经是最优的硬件设计了吗？我了解到可以通过循环平铺和循环展开的方式提高并行度加速卷积计算，在您的代码中是体现在Tm，Tn，Tr，Tc上吗？您的代码中主要使用了“PIPELINE II=2”和“ARRAY_PARTITION”两种pragma，请问如果固定一组Tm，Tn，Tr，Tc，您的代码是否是并行度最高的呢？

十分感谢！

**Comment by Microdent** [comment]
你好，
第一个问题是因为网络每一层的参数和计算量是不固定的，所以cnn.cpp里面的循环次数无法确定，只能由main.cpp传入，所以工具无法显示latency，想要看latency可以手动添加tripcount 的 pragma以告诉工具循环次数的范围；
第二个问题，这并不是最优设计，因为当时参赛给我们预留的比赛时间只有四天，要完成tensorflow的模型训练，tensorflow转c++，c++转HLS再上板调试，所以没有能做太多优化探索，都是以能够运行为目标的，具体调整Tm，Tn，Tr，Tc需要测试比如输入、卷积、全连接、输出各个模块的latency来实现流水线匹配，构建AXI总线带宽与算力的Roofline模型来估算等。除了Pipeline以及Array Partition，还可以尝试类似dataflow等优化方法。

**Comment by Ronin3502** [comment]
十分感谢您的解答，看来我还需要深入学习一下HLS的知识，再次感谢您的分享和指导！
