### ISSUE TITLE
关于Padding

### ISSUE THREAD

**Issue by Ronin3502** [Microdent/Handwritten_Mathematical_Calculator_on_FPGA#8]
您好！请问您的代码中，下面截图红圈部分是在做padding吗？padding的大小是2？
![padding](https://user-images.githubusercontent.com/49109408/163147879-a78a6d55-f69c-4123-9bcb-dd2219506f4e.png)
您的代码中，Tn，Tm，Tr，Tc这四个参数是通过#define定义的，那么每一层的input buffer，weight buffer，以及output buffer，大小都是一样的？
请问TN，TM，TR，TC这四个参数和Tn，Tm，Tr，Tc这四个参数有什么区别呢？其意义又分别是什么呢？
谢谢！

**Comment by Microdent** [comment]
因为卷积采用的是5x5的kernel，所以padding的大小是2，常见的3x3卷积的padding才是1。
每一层所需的input_buffer，weight_buffer，output_buffer的大小都是不一样的，但是硬件综合后buffer大小不可变，所以按照最大的参数来分配buffer空间。
TN，TM，TR，TC是每一层在输入通道、输出通道、高度、宽度上需要循环的次数，Tn，Tm，Tr，Tc是FPGA每一次计算时的输入通道数、输出通道数、高度、宽度，前者代表当前层所有的数据量，后者代表FPGA每次处理的数据量。

**Comment by Ronin3502** [comment]
十分感谢您的回答！
不好意思，我还有一个问题，能帮我解答一下吗？
如下图：
![image](https://user-images.githubusercontent.com/49109408/163723622-5d3d5c6d-8fc2-4525-b6c4-6187e32b2955.png)
将情况简化一些，只考虑2维，且padding=0（设置该层的padding=0），layer i的output被切成了4块，在写入RAM的时候，需要两层循环，如果我们按照内层循环遍历列，外层循环遍历行来写入RAM，然后再按照同样的循环次序load到layer i+1的输入。假设layer i+1的input按照计算得到一个tile的Tr(in)=4, Tc(in)=4，那么load进来的tile1会是左下角的样子吧？但正确load进来的tile 1应该是右下角那样的吧？
请问这样理解是正确的吗？如果是正确的，那么这样进行卷积，计算了一下，结果会发生变化。
想了两天了，没想明白，还请大佬解惑！谢谢！

**Comment by Microdent** [comment]
RAM中的像素排列不能根据切的块来排，应该根据实际图片的像素点顺序排列，也就是123123_789789_456456。

**Comment by Ronin3502** [comment]
但如果按照cnn.cpp代码中，output_write方法所写，程序会将output一个tile一个tile地写入RAM中，在RAM中，输出是否就会变成123789456_123789456...呢？如下图：
![image](https://user-images.githubusercontent.com/49109408/163784346-e38df85f-decb-427c-bb07-5ec2a206eb34.png)
然后读入的时候，在input_load_conv方法中，程序也是从RAM中依次读入数据到input_buffer中，假设layer i+1的buffer的长宽都是4，且RAM中的feature map存储的是123123_789789_456456...，那么读入之后的第一个input tile就应该是：
1231
2378
9789
4564
而从layer i的输出feature map来看，应该是：
1231
7897
4564
1231
如果写入RAM的顺序是按照我理解的顺序，即123789456_123789456...，layer i+1读入的结果又不一样了。
下图是input_load_conv的代码截图：
![image](https://user-images.githubusercontent.com/49109408/163785705-d582ec8c-47d6-4350-bc66-8b62544b183e.png)

**Comment by Microdent** [comment]
这个项目用到的图片尺寸很小，最大也就是32*32，所以实际上FPGA每次都能计算完整的一张图片，没有做Row和Col方向的切块，所以不存在这个问题。

**Comment by Ronin3502** [comment]
好嘞，明白了，感谢大佬指导👍
